### ISSUE TITLE
The "verification" plot auto scale makes it hard to see that the correction was useful.

### ISSUE THREAD

**Issue by jeanconn** [sot/correct_periscope_drift#10]
I don't think I have a good way to fix this, because the plots that I'm using in the docs are the actual output plots from the tool.  I think we need those plots to autoscale, though perhaps I could set a minimum value for the y axis range.

**Comment by taldcroft** [comment]
:+1: on a minimum scale which is always symmetric (zero is at the center).

**Comment by jeanconn** [comment]
When we exceed the minimum range, do we still want the plots to be symmetric?  No biggie either way.

**Comment by taldcroft** [comment]
Yes, e.g. https://github.com/sot/aimpoint_mon/blob/master/update_observed_aimpoints.py#L334

**Comment by jeanconn** [comment]
Closed by a511433
