### ISSUE TITLE
Evaluate 17128 as example

### ISSUE THREAD

**Issue by jeanconn** [sot/correct_periscope_drift#14]
Obsid 17128 has just become public/archived and is a good/better example of an observation with a bright source and uncorrected drift.  Would it be a better example for the docs?

Here are some fit plots for it.  I set the polynomial degree to 8 and have probably overfit it.

![corr_fit_fit_yag](https://cloud.githubusercontent.com/assets/791508/18559698/69f50100-7b46-11e6-8cde-055d5656a74f.png)
![corr_fit_fit_zag](https://cloud.githubusercontent.com/assets/791508/18559697/69efdfcc-7b46-11e6-9abb-84e5ca1ca4cf.png)

**Comment by taldcroft** [comment]
Looks great, but the polynomial degree is probably too high.  I would go with line or at most quadratic.

**Comment by jeanconn** [comment]
Gotcha.  I've got the tool set for quadratic by default, I just wasn't sure if our example looked better or worse if we fit all the wiggles in the zag data.

**Comment by taldcroft** [comment]
We don't want to give an implicit endorsement of applying high-order corrections.  I'm not sure it is justified, so that is a "science" decision users can make on their own.

**Comment by jeanconn** [comment]
Closed by #16  (which was set with a quadratic).
