### ISSUE TITLE
Is the ROLL_PNT from the event file sufficient as a reference?

### ISSUE THREAD

**Issue by jeanconn** [sot/correct_periscope_drift#2]
To align the X-ray events with the the Y and Z aspect camera axis, the code is using a reference point and ROLL_PNT. Is that sufficient?  What is the best way to define "sufficient"?
- Should the code use the roll at the time of each event using the full aspect solution? 
- Should the code use its own calculated median/mean of roll from the given aspect solution? 
- Does the code need to use the aspect camera misalignment?

**Comment by taldcroft** [comment]
Given all the other uncertainties, if the roll is within +/- 3 degrees then there will be no discernable impact on the science result.  So I think the answers to the bulleted questions are No, No, and No.

**Comment by jeanconn** [comment]
Great!   We'd already talked about the last bullet and said no at that time (my only thought on it at this point was that is an easy tweak to make if we decide to do it).  

But, regarding my "what is the best way to define 'sufficient'" question, I think the within 3 degrees makes a lot of sense.  However, it looks like there is some effort within the code of these user tools to be robust to weird inputs, I still wonder if I might as well explicitly check that we're within 3 degrees, or just calculate a value myself per the second question.  Will table for now.

**Comment by taldcroft** [comment]
Even 10 degrees would not cause much issue.  Is there an opportunity for the user to input the roll?

**Comment by jeanconn** [comment]
There's no opportunity for the user to input the roll.  I'm not sure what the tool would do/see if the user hands it a munged or merged dataset.

**Comment by taldcroft** [comment]
Can we close this with a "yes"to the original question?

**Comment by jeanconn** [comment]
Yes.
